name: Compare and Upload to S3

on:
  push:
    branches:
      - master

jobs:
  compare-and-upload:
    runs-on: windows-latest

    env:
      LOCAL_PATH: "F:\\INTEGRATED-PROJECTS\\Softwares\\ipx.bimops\\src\\ipx.bimops.installers.frontend.net8\\Releases"  
      S3_PREFIX: "s3://iso-plugin-bucket/Releases/"  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: List Files in S3
      shell: pwsh
      run: |
        aws s3 ls $env:S3_PREFIX --recursive --summarize | Select-String '\.nupkg$' > s3_files.txt
        Write-Host "S3 .nupkg files:"
        Get-Content s3_files.txt

    - name: Extract Latest Version from S3
      shell: pwsh
      run: |
        $S3_LATEST = Get-Content s3_files.txt | 
                     Select-String 'Iso-' | 
                     ForEach-Object { $_.Matches.Value -replace '.*Iso-([0-9.]+)-.*', '$1' } | 
                     Sort-Object -Version | Select-Object -Last 1
        Write-Host "S3 latest version: $S3_LATEST"
        echo "S3_LATEST=$S3_LATEST" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Extract Latest Version from Local Server
      shell: pwsh
      run: |
        $LOCAL_LATEST = Get-ChildItem -Path $env:LOCAL_PATH | 
                        Where-Object { $_.Name -match 'Iso-' } |
                        ForEach-Object { $_.Name -replace '.*Iso-([0-9.]+)-.*', '$1' } | 
                        Sort-Object -Version | Select-Object -Last 1
        Write-Host "Local latest version: $LOCAL_LATEST"
        echo "LOCAL_LATEST=$LOCAL_LATEST" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Compare Versions and Upload if Needed
      if: ${{ env.LOCAL_LATEST > env.S3_LATEST }}
      shell: pwsh
      run: |
        Write-Host "Newer version found locally. Uploading artifacts..."
        aws s3 cp "$env:LOCAL_PATH\Iso-$env:LOCAL_LATEST-delta.nupkg" "$env:S3_PREFIX/Iso-$env:LOCAL_LATEST-delta.nupkg"
        aws s3 cp "$env:LOCAL_PATH\Iso-$env:LOCAL_LATEST-full.nupkg" "$env:S3_PREFIX/Iso-$env:LOCAL_LATEST-full.nupkg"
        aws s3 cp "$env:LOCAL_PATH\RELEASES.file" "$env:S3_PREFIX/RELEASES.file"

    - name: No New Version Found
      if: ${{ env.LOCAL_LATEST <= env.S3_LATEST }}
      shell: pwsh
      run: Write-Host "No newer version found. Skipping upload."
